# Question
Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log('Inside the loop', i);
  }
  console.log('Outside the loop');
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer
The "console.log('Outside the loop');" will not run because inside the loop is terminated when i is more than 3. In this case, the function terminates at the end of the iterations because i<5 will only run 4 iterations and 4 is more than 5.

# Teacher Feedback
